# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Desktop/ddr_new/ddr_new.srcs/sources_1/ip/dist_dmem_ip/dist_dmem_ip.xci
# IP: The module: 'dist_dmem_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/ddr_new/ddr_new.srcs/sources_1/ip/dist_dmem_ip/dist_dmem_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_dmem_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Desktop/ddr_new/ddr_new.srcs/sources_1/ip/dist_dmem_ip/dist_dmem_ip.xci
# IP: The module: 'dist_dmem_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/ddr_new/ddr_new.srcs/sources_1/ip/dist_dmem_ip/dist_dmem_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_dmem_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
